config/routes.rb
Rails.application.routes.draw do
  resources :mycontacts
  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'
  
  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  
  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'
  
  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/:id', to: 'blogconfigs#edit'
  patch 'blogconfigs/:id', to: 'blogconfigs#edit'

  get 'messages/index'
  get 'messages', to: 'messages#index'

  get 'messages/add'
  post 'messages/add', to: 'messages#create'

  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'
  
  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'books/index'
  get 'books', to: 'books#index'

  get 'books/edit'

  get 'books/add'
  post 'books/add'
  
  get 'books/show/:id', to: 'books#show'

  get 'cards', to: 'cards#index'
  get 'cards/index'

  get 'cards/add'
  post 'cards/add'#, to: 'cards#add'

  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'
  
  get 'cards/delete/:id', to: 'cards#delete'
  
  get 'cards/:id', to: 'cards#show'
  
  

  get 'people/index'
  get 'people', to: 'people#index'
  
  get 'people/add'
  post 'people/add', to: 'people#create'
  
  get 'people/find'
  post 'people/find'
  
  get 'people/edit/:id', to: 'people#edit'
  patch 'people/edit/:id', to: 'people#update'
  
  get 'people/delete/:id', to: 'people#delete'
  
  get 'people/:id', to: 'people#show'
  
  

  get 'dengonban', to: 'dengonban#index'
  post 'dengonban', to: 'dengonban#index'
  get 'dengonban/index'
  post 'dengonban/index'
  
  
  
  get 'helo/index'
	get 'helo', to: 'helo#index'
  post 'helo', to: 'helo#index'
  post 'helo/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
    validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
	has_many :blogpost


	validates :name, presence: {message:'は、必須項目です。'}
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :bloggenre
	
	validates :title, :content, presence: {message:'は、必須項目です。'}
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator


	def validate_each(record, attribute, value)
		unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
			record.errors[attribute] << (options[:message] || "is not an email")
		end
	end


end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :person
    
    validates :message, presence: {message:'を書いてください'}
    
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
	validates :name, presence: {message:'は、必須項目です。'}
	validates :age, numericality: {greater_than: 0, message:'は、数字で入力ください。'}
	validates :nationality, inclusion: {in: [true, false], message:'は、真偽値です。'}
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :message
    
    validates :name, presence: { message: 'は必須項目です。'}
    validates :age, numericality: { message: 'は数字で入力してください。'}
    validates :mail, email: {message: '正しいメールアドレスを入力してください'}
    
end

app/controllers/mycontacts_controller.rb
class MycontactsController < ApplicationController
  before_action :set_mycontact, only: [:show, :edit, :update, :destroy]

  # GET /mycontacts
  # GET /mycontacts.json
  def index
    @mycontacts = Mycontact.all
  end

  # GET /mycontacts/1
  # GET /mycontacts/1.json
  def show
  end

  # GET /mycontacts/new
  def new
    @mycontact = Mycontact.new
  end

  # GET /mycontacts/1/edit
  def edit
  end

  # POST /mycontacts
  # POST /mycontacts.json
  def create
    @mycontact = Mycontact.new(mycontact_params)

    respond_to do |format|
      if @mycontact.save
        format.html { redirect_to @mycontact, notice: 'Mycontact was successfully created.' }
        format.json { render :show, status: :created, location: @mycontact }
      else
        format.html { render :new }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mycontacts/1
  # PATCH/PUT /mycontacts/1.json
  def update
    respond_to do |format|
      if @mycontact.update(mycontact_params)
        format.html { redirect_to @mycontact, notice: 'Mycontact was successfully updated.' }
        format.json { render :show, status: :ok, location: @mycontact }
      else
        format.html { render :edit }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycontacts/1
  # DELETE /mycontacts/1.json
  def destroy
    @mycontact.destroy
    respond_to do |format|
      format.html { redirect_to mycontacts_url, notice: 'Mycontact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycontact
      @mycontact = Mycontact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mycontact_params
      params.require(:mycontact).permit(:name, :age, :nationality, :mail, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggenres_helper.rb
module BloggenresHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/dengonban_helper.rb
module DengonbanHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mycontacts_helper.rb
module MycontactsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/mycontacts/_form.html.erb
<%= form_with(model: mycontact, local: true) do |form| %>
  <% if mycontact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mycontact.errors.count, "error") %> prohibited this mycontact from being saved:</h2>

      <ul>
      <% mycontact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, id: :mycontact_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :mycontact_age %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.check_box :nationality, id: :mycontact_nationality %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :mycontact_mail %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :mycontact_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mycontacts/edit.html.erb
<h1>Editing Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Show', @mycontact %> |
<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mycontacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Mail</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mycontacts.each do |mycontact| %>
      <tr>
        <td><%= mycontact.name %></td>
        <td><%= mycontact.age %></td>
        <td><%= mycontact.nationality %></td>
        <td><%= mycontact.mail %></td>
        <td><%= mycontact.text %></td>
        <td><%= link_to 'Show', mycontact %></td>
        <td><%= link_to 'Edit', edit_mycontact_path(mycontact) %></td>
        <td><%= link_to 'Destroy', mycontact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mycontact', new_mycontact_path %>

app/views/mycontacts/new.html.erb
<h1>New Mycontact</h1>

<%= render 'form', mycontact: @mycontact %>

<%= link_to 'Back', mycontacts_path %>

app/views/mycontacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mycontact.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @mycontact.age %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @mycontact.nationality %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mycontact.mail %>
</p>

<p>
  <strong>Text:</strong>
  <%= @mycontact.text %>
</p>

<%= link_to 'Edit', edit_mycontact_path(@mycontact) %> |
<%= link_to 'Back', mycontacts_path %>